# Generated by Django 3.1.2 on 2020-12-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('sr', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=15)),
                ('NoOfLogs', models.IntegerField(default=0)),
            ],
        ),
    ]
