# Generated by Django 3.1.3 on 2020-12-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification',
            field=models.IntegerField(default=0),
        ),
    ]
