# Generated by Django 3.1.3 on 2020-12-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_verification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
