# Generated by Django 3.1.3 on 2020-12-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='noOfLogs',
            field=models.IntegerField(default=0),
        ),
    ]
