# Generated by Django 3.1.3 on 2020-12-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_newuser_nooflogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='verification_code',
            field=models.IntegerField(default=0),
        ),
    ]
